using VelrixWorkHub.Application.Customers;
using VelrixWorkHub.Application.Inventory;
using VelrixWorkHub.Application.Products;
using VelrixWorkHub.Application.Warehouses;
using VelrixWorkHub.Application.Settlements;
using VelrixWorkHub.Domain;
using VelrixWorkHub.Application.PmsProjects;
using VelrixWorkHub.Application.Workflow;
namespace VelrixWorkHub.Application.SalesOrders;
public sealed class SalesOrderService(ISalesOrderRepository repository, ICustomerRepository customerRepository, IProductRepository productRepository, InventoryService inventoryService, IWarehouseRepository warehouseRepository, VelrixWorkHub.Application.Contracts.SalesContractService contractService, ISettlementRepository settlementRepository, IPmsProjectRepository? projectRepository = null, WorkflowApprovalService? approval = null) : ISalesOrderWorkflowApprover
{
    public IReadOnlyList<SalesOrder> List(string? keyword = null) { var query = repository.List().AsEnumerable(); var text = keyword?.Trim(); if (!string.IsNullOrWhiteSpace(text)) query = query.Where(x => x.OrderNo.Contains(text, StringComparison.OrdinalIgnoreCase)); return query.OrderByDescending(x => x.OrderDate).ToArray(); }
    public SalesOrder Create(string orderNo, Guid customerId, Guid productId, DateOnly date, decimal quantity, decimal unitPrice, Guid? contractId = null, Guid? pmsProjectId = null, DateOnly? dueDate = null) { var customer = customerRepository.List().FirstOrDefault(x => x.Id == customerId); if (customer is null) throw new InvalidOperationException("客户不存在。"); if (customer.Status != CustomerStatus.Active) throw new InvalidOperationException("客户已停用，不能创建销售订单。"); var product = productRepository.List().FirstOrDefault(x => x.Id == productId); if (product is null) throw new InvalidOperationException("商品不存在。"); if (product.Status != ProductStatus.Active) throw new InvalidOperationException("商品已停用，不能创建销售订单。"); if (contractId is Guid id) { var contract = contractService.List().FirstOrDefault(x => x.Id == id) ?? throw new InvalidOperationException("关联合同不存在。"); if (contract.CustomerId != customerId) throw new InvalidOperationException("关联合同不属于所选客户。"); if (contract.Status != ContractStatus.Active) throw new InvalidOperationException("只有生效合同可以关联销售订单。"); if (date < contract.StartDate || date > contract.EndDate) throw new InvalidOperationException("销售订单日期不在合同有效期内。"); } if (pmsProjectId is Guid projectId) { var project = projectRepository?.List().FirstOrDefault(x => x.Id == projectId) ?? throw new InvalidOperationException("关联项目不存在。"); if (project.CustomerId != customerId) throw new InvalidOperationException("关联项目不属于所选客户。"); if (project.Status == PmsProjectStatus.Cancelled) throw new InvalidOperationException("已取消项目不能关联销售订单。"); } var item = new SalesOrder(orderNo, customerId, productId, date, quantity, unitPrice, contractId, pmsProjectId, dueDate); if (repository.List().Any(x => x.OrderNo.Equals(item.OrderNo, StringComparison.OrdinalIgnoreCase))) throw new InvalidOperationException("销售订单号已存在。"); repository.Add(item); return item; }
    public void SetStatus(SalesOrder item, SalesOrderStatus status) { if (status == SalesOrderStatus.Submitted && item.Status == SalesOrderStatus.Draft) approval?.RequireCompleted(WorkflowBindingCodes.SalesOrderApproval, nameof(SalesOrder), item.Id, "销售订单提交"); EnsureCanChangeStatus(item, status); item.SetStatus(status); repository.Update(item); }
    public void ApplyApproval(SalesOrder item)
    {
        if (item.Status == SalesOrderStatus.Submitted) return;
        if (item.Status != SalesOrderStatus.Draft) throw new InvalidOperationException($"销售订单不能从“{item.Status}”通过审批。");
        item.SetStatus(SalesOrderStatus.Submitted);
        repository.Update(item);
    }
    public void Ship(SalesOrder item) { if (item.Status != SalesOrderStatus.Submitted) throw new InvalidOperationException("只有已提交的销售订单可以出库。"); var warehouse = warehouseRepository.List().FirstOrDefault(x => x.Status == WarehouseStatus.Active) ?? throw new InvalidOperationException("没有可用的启用仓库。"); var sourceNo = $"{item.OrderNo}-OUT"; if (inventoryService.List().Any(x => x.SourceNo.Equals(sourceNo, StringComparison.OrdinalIgnoreCase))) throw new InvalidOperationException("该销售订单已生成出库流水。"); var balance = inventoryService.Balances().FirstOrDefault(x => x.ProductId == item.ProductId && x.WarehouseId == warehouse.Id)?.Quantity ?? 0; if (balance < item.Quantity) throw new InvalidOperationException($"库存不足，当前可用库存为 {balance:N2}。"); item.SetStatus(SalesOrderStatus.Shipped); repository.Update(item); inventoryService.Create(item.ProductId, warehouse.Id, InventoryTransactionKind.Outbound, item.Quantity, sourceNo, item.OrderDate, $"销售订单 {item.OrderNo} 出库"); }
    private void EnsureCanChangeStatus(SalesOrder item, SalesOrderStatus status) { if (status == SalesOrderStatus.Cancelled) { approval?.RequireNotRunning(WorkflowBindingCodes.SalesOrderApproval, nameof(SalesOrder), item.Id, "取消销售订单"); if (settlementRepository.List().Any(x => x.OrderId == item.Id && x.Kind == ErpSettlementKind.Receivable && x.Status == ErpSettlementStatus.Active)) throw new InvalidOperationException("销售订单已有有效收款核销，不能取消订单；请先撤销核销。"); } }
}
