namespace VelrixWorkHub.Domain;
public enum SalesOrderStatus { Draft, Submitted, Shipped, Cancelled }
public sealed class SalesOrder
{
    public Guid Id { get; init; } = Guid.CreateVersion7(); public string OrderNo { get; private set; } = string.Empty; public Guid CustomerId { get; private set; } public Guid ProductId { get; private set; } public Guid? ContractId { get; private set; } public Guid? PmsProjectId { get; private set; } public DateOnly OrderDate { get; private set; } public DateOnly DueDate { get; private set; } public decimal Quantity { get; private set; } public decimal UnitPrice { get; private set; } public SalesOrderStatus Status { get; private set; } public decimal Amount => decimal.Round(Quantity * UnitPrice, 2);
    public SalesOrder(string orderNo, Guid customerId, Guid productId, DateOnly date, decimal quantity, decimal unitPrice, Guid? contractId = null, Guid? pmsProjectId = null, DateOnly? dueDate = null) { if (string.IsNullOrWhiteSpace(orderNo)) throw new ArgumentException("销售订单号不能为空。", nameof(orderNo)); if (customerId == Guid.Empty) throw new ArgumentException("必须选择客户。", nameof(customerId)); if (productId == Guid.Empty) throw new ArgumentException("必须选择商品。", nameof(productId)); if (quantity <= 0) throw new ArgumentOutOfRangeException(nameof(quantity), "销售数量必须大于 0。"); if (unitPrice < 0) throw new ArgumentOutOfRangeException(nameof(unitPrice), "销售单价不能为负数。"); var resolvedDueDate = dueDate ?? date.AddDays(30); if (resolvedDueDate < date) throw new ArgumentException("收款到期日不能早于订单日期。", nameof(dueDate)); OrderNo = orderNo.Trim(); CustomerId = customerId; ProductId = productId; ContractId = contractId; PmsProjectId = pmsProjectId; OrderDate = date; DueDate = resolvedDueDate; Quantity = quantity; UnitPrice = unitPrice; Status = SalesOrderStatus.Draft; }
    public void SetStatus(SalesOrderStatus status) { if (status == Status) return; var allowed = (Status, status) switch { (SalesOrderStatus.Draft, SalesOrderStatus.Submitted) => true, (SalesOrderStatus.Draft, SalesOrderStatus.Cancelled) => true, (SalesOrderStatus.Submitted, SalesOrderStatus.Shipped) => true, (SalesOrderStatus.Submitted, SalesOrderStatus.Cancelled) => true, _ => false }; if (!allowed) throw new InvalidOperationException($"销售订单不能从“{Status}”变更为“{status}”。"); Status = status; }
    public static SalesOrder Restore(Guid id, string orderNo, Guid customerId, Guid productId, DateOnly date, decimal quantity, decimal unitPrice, SalesOrderStatus status, Guid? contractId = null, Guid? pmsProjectId = null, DateOnly? dueDate = null) { var item = new SalesOrder(orderNo, customerId, productId, date, quantity, unitPrice, contractId, pmsProjectId, dueDate) { Id = id }; item.Status = status; return item; }
}
