using FreeSql; using VelrixWorkHub.Application.Lms; using VelrixWorkHub.Domain;
namespace VelrixWorkHub.Infrastructure.Lms;
public sealed class FreeSqlLmsLicenseRepository(IFreeSql fsql) : ILmsLicenseRepository
{
    public IReadOnlyList<LmsLicenseRequest> ListRequests() => fsql.Select<LmsLicenseRequestRecord>().ToList().Select(x => { var item = new LmsLicenseRequest(x.RequestNo,x.Applicant,x.ProductName,x.CustomerName,x.FeaturesJson,x.RequestedExpiresAt,x.OtherInfo,x.CreatedAt,x.CustomerId,x.CustomerMachineId,x.FeatureVersionIdsJson,x.ContactId,x.Model,x.Environment,x.GracePeriodDays){Id=x.Id}; item.SetStatus(x.Status); return item; }).ToArray();
    public IReadOnlyList<LmsLicenseAuthorization> ListAuthorizations() => fsql.Select<LmsLicenseAuthorizationRecord>().ToList().Select(x => { var item = new LmsLicenseAuthorization(x.RequestId,x.LicenseNo,x.ExternalLicense,x.ProductName,x.FeaturesJson,x.ExpiresAt,x.OtherInfo,x.CreatedAt,x.CustomerId,x.CustomerMachineId,x.FeatureVersionIdsJson,x.ContactId,x.SupersedesAuthorizationId,x.ReplacementKind,x.ReplacementRequestId,x.Model,x.Environment,x.GracePeriodDays){Id=x.Id}; item.SetStatus(x.Status); return item; }).ToArray();
    public IReadOnlyList<LmsLicenseLifecycleEntry> ListLifecycleEntries(Guid authorizationId) => fsql.Select<LmsLicenseLifecycleEntryRecord>().Where(x => x.AuthorizationId == authorizationId).ToList().Select(x => new LmsLicenseLifecycleEntry(x.AuthorizationId,x.Action,x.PreviousStatus,x.CurrentStatus,x.Actor,x.Reason,x.OccurredAt){Id=x.Id}).ToArray();
    public void Add(LmsLicenseRequest x) => fsql.Insert(new LmsLicenseRequestRecord{Id=x.Id,RequestNo=x.RequestNo,Applicant=x.Applicant,ProductName=x.ProductName,CustomerId=x.CustomerId,ContactId=x.ContactId,CustomerMachineId=x.CustomerMachineId,CustomerName=x.CustomerName,FeaturesJson=x.FeaturesJson,FeatureVersionIdsJson=x.FeatureVersionIdsJson,RequestedExpiresAt=x.RequestedExpiresAt,OtherInfo=x.OtherInfo,Status=x.Status,CreatedAt=x.CreatedAt,Model=x.Model,Environment=x.Environment,GracePeriodDays=x.GracePeriodDays}).ExecuteAffrows();
    public void Update(LmsLicenseRequest x) { if(fsql.Update<LmsLicenseRequestRecord>().Set(a=>a.Status,x.Status).Where(a=>a.Id==x.Id).ExecuteAffrows()==0) throw new InvalidOperationException("许可证申请不存在。"); }
    public void RemoveRequest(Guid requestId) { if (fsql.Delete<LmsLicenseRequestRecord>().Where(x => x.Id == requestId).ExecuteAffrows() == 0) throw new InvalidOperationException("许可证申请不存在。"); }
    public void Add(LmsLicenseAuthorization x) => fsql.Insert(new LmsLicenseAuthorizationRecord{Id=x.Id,RequestId=x.RequestId,SupersedesAuthorizationId=x.SupersedesAuthorizationId,ReplacementKind=x.ReplacementKind,LicenseNo=x.LicenseNo,ExternalLicense=x.ExternalLicense,ProductName=x.ProductName,CustomerId=x.CustomerId,ContactId=x.ContactId,CustomerMachineId=x.CustomerMachineId,FeaturesJson=x.FeaturesJson,FeatureVersionIdsJson=x.FeatureVersionIdsJson,ExpiresAt=x.ExpiresAt,OtherInfo=x.OtherInfo,Status=x.Status,CreatedAt=x.CreatedAt,ReplacementRequestId=x.ReplacementRequestId,Model=x.Model,Environment=x.Environment,GracePeriodDays=x.GracePeriodDays}).ExecuteAffrows();
    public void Update(LmsLicenseAuthorization x) { if(fsql.Update<LmsLicenseAuthorizationRecord>().Set(a=>a.Status,x.Status).Where(a=>a.Id==x.Id).ExecuteAffrows()==0) throw new InvalidOperationException("许可证授权不存在。"); }
    public void Add(LmsLicenseLifecycleEntry x) => fsql.Insert(new LmsLicenseLifecycleEntryRecord{Id=x.Id,AuthorizationId=x.AuthorizationId,Action=x.Action,PreviousStatus=x.PreviousStatus,CurrentStatus=x.CurrentStatus,Actor=x.Actor,Reason=x.Reason,OccurredAt=x.OccurredAt}).ExecuteAffrows();
}
